export default class Config {
  static API_KEY = '47a7085127ae49a25727d14a6a229052'
  static BASE_URL = 'https://api.themoviedb.org/3/'
  static IMAGE_URL = 'http://image.tmdb.org/t/p/'
  static FIREBASE_API_KEY = 'AIzaSyBzqg2jWVJr_kMf3L7eoB6ixM3JSPXSKUw'
  static FIREBASE_AUTH_DOMAIN = 'movies-app-a49c8.firebaseapp.com'
  static FIREBASE_DATABASE_URL = 'https://movies-app-a49c8.firebaseio.com'
  static FIREBASE_PROJECT_ID = 'movies-app-a49c8'
  static FIREBASE_STORAGE_BUCKET = 'movies-app-a49c8.appspot.com'
  static FIREBASE_MESSAGE_SENDER_ID = '555164613924'
  static IMDB_API = 'http://www.omdbapi.com/?apikey=381b5f9f'
  static ALGOLIA_APP_ID = '2SJ97GYD7X'
  static ALGOLIA_API_KEY = '4d4a7659449c9f6df236475f25f82923'
  static ALGOLIA_ADMIN_KEY = '9c6e5587e8d4a897405cdded5f893aae'
  static ALGOLIA_MOVIES_INDEX_NAME = 'movies'
  static ALGOLIA_USERS_INDEX_NAME = 'users'
  static EXPO_PUSH_SERVER = 'https://exp.host/--/api/v2/push/send'
  static CINEMAS_API_BASE_URL = 'https://api-gate2.movieglu.com/'
  static CINEMAS_API_USERNAME = 'SHEF'
  static CINEMAS_API_X_KEY = '5cDtwKRic8aibIS8R22N86TxrBojNKmDaiFxMnmY'
  static CINEMAS_API_AUTH = 'Basic U0hFRjpEQVBpUU9aNGJaam0='
}
